# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bddd79210b68e5a67f58ef97102cdba9f12534fab30475a67ca56c555971257df10d39e0fbf55ce04ae3a5e860c5cbeb79328ca1242b0e0d9554447b0d2cfb4a

test:
  secret_key_base: 1ecbd11ebbdfa3f63b9c63d8cff5ddb3f6412389bec5ead4a2e15ab128fd3f1d183d6182aa1012bff6f45272b6946135fa99f1a15a64bd33a2ff023e2cdf384e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
